version: '3.8'

services:
  chukapoka-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: sinhyunjin/chukapoka-server:latest
    ports:
      - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/tree
      SPRING_DATASOURCE_USERNAME: tree
      SPRING_DATASOURCE_PASSWORD: tree
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: sinhyunjin/postgres-db:latest
    environment:
      POSTGRES_DB: tree
      POSTGRES_USER: tree
      POSTGRES_PASSWORD: tree
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - chukapoka-server
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
